### ISSUE TITLE
与插件 siyuan-oembed 在工具栏上存在冲突

### ISSUE THREAD

**Issue by QMike0** [Achuan-2/siyuan-plugin-formatPainter#2]
当启用插件 siyuan-oembed 后，它在工具栏的两个按钮会将本插件的按钮覆盖掉
- 不启用插件 siyuan-oembed ：
  ![1730865906443](https://github.com/user-attachments/assets/6e17dd8b-8058-4bd4-8eee-0f62485f4484)

- 启用插件 siyuan-oembed 后：
  ![1730865961145](https://github.com/user-attachments/assets/f40f0620-2f7d-4550-a0c1-66f02687570e)

不知道是哪个插件的问题，所以暂时先在这里提一下issue

**Comment by Achuan-2** [comment]
这个插件没上架集市吗，没见过
感觉是这个插件的问题，我用的是官方提供的方法添加按钮的

**Comment by Achuan-2** [comment]
应该是思源提供的插件功能存在一定缺陷：https://github.com/siyuan-note/plugin-sample/issues/24

**Comment by Achuan-2** [comment]
https://github.com/Achuan-2/siyuan-plugin-formatPainter/commit/09a8b17def60ec4e6f00bcadc7ba358201380fdd
